# Generated by Django 5.2.4 on 2025-08-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einkaufszettel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='zettel',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('zettel', 'slug'), name='unique_item_slug_per_zettel'),
        ),
    ]
