# Generated by Django 5.2.4 on 2025-08-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einkaufszettel', '0003_populate_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zettel',
            name='slug',
            field=models.CharField(editable=False, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
